-- Create USERS table
CREATE TABLE USERS (
    USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);

-- Create unique index on email
CREATE UNIQUE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
